<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * A drawer based layout for the boost theme.
 *
 * @package   theme_boost
 * @copyright 2021 Bas Brands
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

// Output the main content of the page.
echo $OUTPUT->main_content();

$templatecontext['custom_message'] = '<p>This is my custom message.</p>';

// Define your HTML content as a string
$html_content = <<<HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
  </head>
  <body>
    <h1>My Custom Page</h1>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
HTML;

// Add your HTML content to the $templatecontext array
$templatecontext['html_content'] = $html_content;

// Render the template with the custom context
echo $OUTPUT->render_from_template('theme_noba/mycustompage', $templatecontext);
