<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * A drawer based layout for the boost theme.
 *
 * @package   theme_boost
 * @copyright 2021 Bas Brands
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

// Output the main content of the page.
echo $OUTPUT->main_content();

$templatecontext['custom_message'] = '<p>This is my custom message.</p>';

// Define your HTML content as a string
$html_content = <<<HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=GT+Walsheim:wght@400;500&display=swap" />
    <link rel="stylesheet" href="index.css" />
  </head>
  <body>
  <div class="main-container">
      <div class="rectangle">
        <div class="icon-profile-white">
          <div class="derek-profile"><div class="group"></div></div>
        </div>
        <div class="icon-chat"></div>
        <div class="icon-notification-white"></div>
        <div class="single-line-white"></div>
        <span class="sign-in">Sign out</span>
      </div>
      <div class="rectangle-1">
        <div class="rectangle-2">
          <div class="rectangle-3">
            <div class="rectangle-4"></div>
            <div class="rectangle-5"></div>
            <div class="rectangle-6"></div>
            <div class="rectangle-7"></div>
            <div class="rectangle-8"></div>
            <div class="overlay">
              <div class="noba-academyportal-icon-report"></div>
              <span class="academy-dashboard">Dashboard</span>
            </div>
            <div class="dashboard"></div>
            <div class="community"></div>
            <div class="lms"></div>
            <div class="exams"></div>
            <span class="academy">Community</span
            ><span class="academy-9">Settings</span
            ><span class="academy-a">Learn</span
            ><span class="academy-b">Tests</span>
          </div>
          <div class="flex-row">
            <div class="rectangle-c">
              <div class="users">
                <span class="great-work-this-week">Great work this week, </span
                ><span class="sarina">Sarina</span
                ><span class="keep-it-up">. Keep it up!</span>
              </div>
              <span class="weekly-target"
                >You’re 82% towards your weekly target.</span
              ><span class="set-goal">Set goal</span>
            </div>
            <div class="ellipse"></div>
            <div class="ellipse-d"></div>
            <span class="average-score">Courses in progress</span
            ><span class="average-score-e">Average score</span
            ><span class="percentage">3</span
            ><span class="percentage-f">91%</span>
            <div class="component"></div>
            <div class="ellipse-10"></div>
            <span class="view-all-data">View all data</span
            ><span class="get-full-report">Continue</span
            ><span class="get-full-report-11">Get full report</span
            ><span class="average-score-12">Courses completed</span
            ><span class="average-score-13">Learning this week (hrs)</span
            ><span class="percentage-14">2</span
            ><span class="percentage-15">3.4</span
            ><span class="get-full-report-16">View progress</span
            ><span class="get-full-report-17">See all activity</span>
          </div>
          <div class="ellipse-18"></div>
        </div>
      </div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
HTML;

// Add your HTML content to the $templatecontext array
$templatecontext['html_content'] = $html_content;

// Render the template with the custom context
echo $OUTPUT->render_from_template('theme_noba/mydrawers', $templatecontext);
